package com.screenshare

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.content.pm.ServiceInfo
import android.os.Binder
import android.os.Build
import android.os.IBinder
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import android.util.Log
import androidx.core.app.NotificationCompat
import org.json.JSONArray
import org.json.JSONObject
import org.webrtc.DataChannel
import org.webrtc.EglBase
import org.webrtc.IceCandidate
import org.webrtc.MediaStream
import org.webrtc.PeerConnection
import org.webrtc.RtpReceiver
import org.webrtc.SessionDescription

/**
 * Foreground service that owns the [WebRTCClient] and [SignalingClient] for the broadcaster.
 *
 * Strict 1:1 model: one broadcaster streams to exactly one viewer.
 *
 * DataChannel control messages handled here (broadcaster-side incoming):
 *   buzz          – vibrate this device + Lovense toys
 *   emoji         – floating emoji reaction (relayed to [EmojiListener])
 *   lock          – show/hide the [LockOverlayManager] fullscreen lock
 *   app_violation – relayed outward; normally generated by this device's own
 *                   [RestrictedAppsAccessibilityService]
 */
class ScreenShareService : Service() {

    fun interface StatusListener      { fun onStatus(status: String) }
    fun interface ChatListener        { fun onChatMessage(text: String) }
    fun interface EmojiListener       { fun onEmoji(emoji: String) }
    /** Fired when the broadcaster opened a restricted app (so the activity can show a toast). */
    fun interface ViolationListener   { fun onViolation(appName: String, pkg: String) }

    inner class LocalBinder : Binder() {
        fun getService(): ScreenShareService = this@ScreenShareService
    }

    private val binder = LocalBinder()
    private var statusListener:    StatusListener?    = null
    private var chatListener:      ChatListener?      = null
    private var emojiListener:     EmojiListener?     = null
    private var violationListener: ViolationListener? = null

    private lateinit var eglBase:          EglBase
    private lateinit var webRTCClient:     WebRTCClient
    private lateinit var signalingClient:  SignalingClient
    private lateinit var lockOverlay:      LockOverlayManager

    // -----------------------------------------------------------------------
    // Restricted-app violation receiver
    // -----------------------------------------------------------------------

    private val violationReceiver = object : BroadcastReceiver() {
        override fun onReceive(context: Context, intent: Intent) {
            val pkg     = intent.getStringExtra(RestrictedAppsAccessibilityService.EXTRA_PKG) ?: return
            val appName = intent.getStringExtra(RestrictedAppsAccessibilityService.EXTRA_APP_NAME) ?: pkg
            // Notify the activity.
            violationListener?.onViolation(appName, pkg)
            // Alert the viewer via DataChannel.
            if (::webRTCClient.isInitialized) {
                webRTCClient.sendControlMessage("app_violation", mapOf(
                    "appName" to appName,
                    "pkg" to pkg,
                ))
            }
        }
    }

    // -----------------------------------------------------------------------
    // Service lifecycle
    // -----------------------------------------------------------------------

    override fun onCreate() {
        super.onCreate()
        createNotificationChannel()
        lockOverlay = LockOverlayManager(this)

        val filter = IntentFilter(RestrictedAppsAccessibilityService.ACTION_APP_VIOLATION)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            registerReceiver(violationReceiver, filter, Context.RECEIVER_NOT_EXPORTED)
        } else {
            registerReceiver(violationReceiver, filter)
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        val resultCode = intent?.getIntExtra(EXTRA_RESULT_CODE, -1) ?: -1
        val resultData: Intent? = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            intent?.getParcelableExtra(EXTRA_RESULT_DATA, Intent::class.java)
        } else {
            @Suppress("DEPRECATION")
            intent?.getParcelableExtra(EXTRA_RESULT_DATA)
        }
        val sessionId  = intent?.getStringExtra(EXTRA_SESSION_ID)   ?: ""
        val serverUrl  = intent?.getStringExtra(EXTRA_SERVER_URL)    ?: DEFAULT_SERVER_URL
        val password   = intent?.getStringExtra(EXTRA_PASSWORD)
        val useMic     = intent?.getBooleanExtra(EXTRA_USE_MIC, true) ?: true
        val qualityOrd = intent?.getIntExtra(EXTRA_QUALITY, WebRTCClient.Quality.MEDIUM.ordinal)
            ?: WebRTCClient.Quality.MEDIUM.ordinal
        val quality    = WebRTCClient.Quality.values()[qualityOrd.coerceIn(WebRTCClient.Quality.values().indices)]
        val turnUrl    = intent?.getStringExtra(EXTRA_TURN_URL)
        val turnUser   = intent?.getStringExtra(EXTRA_TURN_USER)
        val turnPass   = intent?.getStringExtra(EXTRA_TURN_PASS)

        @Suppress("UNCHECKED_CAST")
        val restrictedPkgs = (intent?.getSerializableExtra(EXTRA_RESTRICTED_PKGS) as? ArrayList<String>)
            ?.toSet() ?: emptySet()
        RestrictedAppsAccessibilityService.restrictedPackages = restrictedPkgs

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            startForeground(
                NOTIFICATION_ID,
                buildNotification(),
                ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
            )
        } else {
            startForeground(NOTIFICATION_ID, buildNotification())
        }

        if (resultData != null && resultCode != -1) {
            eglBase = EglBase.create()
            setupWebRTC(resultData, quality, useMic, turnUrl, turnUser, turnPass)
            setupSignaling(serverUrl, sessionId, password)
        } else {
            Log.e(TAG, "Missing MediaProjection data; stopping service.")
            sendBroadcast(Intent(ACTION_ERROR).putExtra(EXTRA_ERROR_MESSAGE,
                "Screen capture permission was not granted."))
            stopSelf()
        }

        return START_NOT_STICKY
    }

    override fun onBind(intent: Intent): IBinder = binder

    override fun onDestroy() {
        super.onDestroy()
        unregisterReceiver(violationReceiver)
        RestrictedAppsAccessibilityService.restrictedPackages = emptySet()
        lockOverlay.hide()
        if (::signalingClient.isInitialized) signalingClient.disconnect()
        if (::webRTCClient.isInitialized) webRTCClient.close()
        if (::eglBase.isInitialized) eglBase.release()
    }

    // -----------------------------------------------------------------------
    // Public API (used by BroadcastActivity via the binder)
    // -----------------------------------------------------------------------

    fun setStatusListener(listener: StatusListener?)         { statusListener    = listener }
    fun setChatListener(listener: ChatListener?)             { chatListener      = listener }
    fun setEmojiListener(listener: EmojiListener?)           { emojiListener     = listener }
    fun setViolationListener(listener: ViolationListener?)   { violationListener = listener }

    fun sendChatMessage(text: String) {
        if (::webRTCClient.isInitialized) webRTCClient.sendChatMessage(text)
    }

    /** Sends any control message to the viewer (blackout, freeze, buzz, countdown, etc.). */
    fun sendControl(type: String, extras: Map<String, Any> = emptyMap()) {
        if (::webRTCClient.isInitialized) webRTCClient.sendControlMessage(type, extras)
    }

    /** Freezes or unfreezes the screen capture on both sides. */
    fun freezeFrame(on: Boolean) {
        if (::webRTCClient.isInitialized) {
            webRTCClient.freezeFrame(on)
            webRTCClient.sendControlMessage("freeze", mapOf("on" to on))
        }
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    private fun setupWebRTC(
        resultData: Intent,
        quality: WebRTCClient.Quality,
        useMic: Boolean,
        turnUrl: String?,
        turnUser: String?,
        turnPass: String?,
    ) {
        webRTCClient = WebRTCClient(this, eglBase, object : PeerConnection.Observer {
            override fun onSignalingChange(state: PeerConnection.SignalingState) {}
            override fun onIceConnectionChange(state: PeerConnection.IceConnectionState) {
                updateStatus("ICE: ${state.name}")
            }
            override fun onIceConnectionReceivingChange(b: Boolean) {}
            override fun onIceGatheringChange(state: PeerConnection.IceGatheringState) {}
            override fun onIceCandidate(candidate: IceCandidate) {
                if (::signalingClient.isInitialized) signalingClient.sendIceCandidate(candidate)
            }
            override fun onIceCandidatesRemoved(candidates: Array<IceCandidate>) {}
            override fun onAddStream(stream: MediaStream) {}
            override fun onRemoveStream(stream: MediaStream) {}
            override fun onDataChannel(channel: DataChannel) {}
            override fun onRenegotiationNeeded() {}
            override fun onAddTrack(receiver: RtpReceiver, streams: Array<MediaStream>) {}
        })
        webRTCClient.initializePeerConnection(turnUrl, turnUser, turnPass)
        webRTCClient.startScreenCapture(resultData, quality)
        if (useMic) webRTCClient.startAudioCapture()

        webRTCClient.dataChannelListener = WebRTCClient.DataChannelListener { json ->
            handleIncomingDataMessage(json)
        }
    }

    private fun setupSignaling(serverUrl: String, sessionId: String, password: String?) {
        signalingClient = SignalingClient(serverUrl, object : SignalingClient.ListenerAdapter() {
            override fun onConnected() {
                signalingClient.createSession(sessionId, password)
            }

            override fun onSessionCreated(sessionId: String) {
                updateStatus(getString(R.string.status_waiting_for_viewer))
            }

            override fun onViewerJoined() {
                vibrate(VIBRATE_VIEWER_JOIN)
                updateStatus(getString(R.string.status_viewer_connected))
                webRTCClient.createOffer(object : SimpleSdpObserver() {
                    override fun onCreateSuccess(sdp: SessionDescription) {
                        webRTCClient.setLocalDescription(object : SimpleSdpObserver() {}, sdp)
                        signalingClient.sendOffer(sdp)
                    }
                    override fun onCreateFailure(error: String) {
                        updateStatus("Offer failed: $error")
                    }
                })
            }

            override fun onViewerLeft() {
                updateStatus(getString(R.string.status_waiting_for_viewer))
                // Release the lock if the viewer who set it has disconnected.
                lockOverlay.hide()
            }

            override fun onAnswerReceived(sdp: SessionDescription) {
                webRTCClient.setRemoteDescription(object : SimpleSdpObserver() {
                    override fun onSetSuccess() {
                        updateStatus(getString(R.string.status_streaming))
                    }
                }, sdp)
            }

            override fun onIceCandidateReceived(candidate: IceCandidate) {
                webRTCClient.addIceCandidate(candidate)
            }

            override fun onError(message: String) {
                updateStatus("Error: $message")
            }
        })
        signalingClient.connect()
    }

    /**
     * Handles a JSON control message arriving over the DataChannel (from the viewer).
     *
     * Expected types: buzz | lock | chat
     */
    private fun handleIncomingDataMessage(json: String) {
        try {
            val obj = JSONObject(json)
            when (obj.getString("type")) {
                "chat" -> chatListener?.onChatMessage(obj.optString("text"))

                "buzz" -> {
                    val patternArray = obj.optJSONArray("pattern")
                    val pattern = if (patternArray != null) {
                        LongArray(patternArray.length()) { patternArray.getLong(it) }
                    } else {
                        VIBRATE_BUZZ_DEFAULT
                    }
                    vibrate(pattern)
                    LovenseManager.getInstance(application).vibrate(LOVENSE_BUZZ_LEVEL)
                    // Auto-stop Lovense after the pattern duration.
                    val totalMs = pattern.sum()
                    android.os.Handler(mainLooper).postDelayed({
                        LovenseManager.getInstance(application).stopAll()
                    }, totalMs + 100)
                }

                "emoji" -> {
                    val emoji = obj.optString("value", "❤️")
                    emojiListener?.onEmoji(emoji)
                    vibrate(VIBRATE_EMOJI)
                }

                "lock" -> {
                    val on = obj.optBoolean("on", true)
                    if (on) lockOverlay.show() else lockOverlay.hide()
                }

                "remote_touch" -> {
                    // Forward to the accessibility service via local broadcast so it
                    // can inject the gesture at the OS level via dispatchGesture().
                    sendBroadcast(Intent(RestrictedAppsAccessibilityService.ACTION_REMOTE_TOUCH).apply {
                        putExtra(RestrictedAppsAccessibilityService.EXTRA_TOUCH_JSON, json)
                        `package` = applicationContext.packageName
                    })
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Failed to parse DataChannel message: $json", e)
        }
    }

    private fun updateStatus(status: String) {
        statusListener?.onStatus(status)
    }

    private fun vibrate(pattern: LongArray) {
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                val manager = getSystemService(VibratorManager::class.java)
                manager?.defaultVibrator?.vibrate(VibrationEffect.createWaveform(pattern, -1))
            } else {
                @Suppress("DEPRECATION")
                val vibrator = getSystemService(Context.VIBRATOR_SERVICE) as? Vibrator
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    vibrator?.vibrate(VibrationEffect.createWaveform(pattern, -1))
                } else {
                    @Suppress("DEPRECATION")
                    vibrator?.vibrate(pattern, -1)
                }
            }
        } catch (_: Exception) { /* vibration is best-effort */ }
    }

    private fun buildNotification() = NotificationCompat.Builder(this, CHANNEL_ID)
        .setContentTitle(getString(R.string.notification_title))
        .setContentText(getString(R.string.notification_text))
        .setSmallIcon(R.drawable.ic_cast)
        .setOngoing(true)
        .build()

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                getString(R.string.channel_name),
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = getString(R.string.channel_description)
            }
            getSystemService(NotificationManager::class.java).createNotificationChannel(channel)
        }
    }

    companion object {
        const val EXTRA_RESULT_CODE      = "result_code"
        const val EXTRA_RESULT_DATA      = "result_data"
        const val EXTRA_SESSION_ID       = "session_id"
        const val EXTRA_SERVER_URL       = "server_url"
        const val EXTRA_PASSWORD         = "password"
        const val EXTRA_USE_MIC          = "use_mic"
        const val EXTRA_QUALITY          = "quality"
        const val EXTRA_TURN_URL         = "turn_url"
        const val EXTRA_TURN_USER        = "turn_user"
        const val EXTRA_TURN_PASS        = "turn_pass"
        const val EXTRA_RESTRICTED_PKGS  = "restricted_pkgs"
        const val ACTION_ERROR           = "com.screenshare.ACTION_SERVICE_ERROR"
        const val EXTRA_ERROR_MESSAGE    = "error_message"
        const val DEFAULT_SERVER_URL     = "ws://10.0.2.2:8080"

        private const val CHANNEL_ID      = "screen_share_channel"
        private const val NOTIFICATION_ID = 1
        private const val TAG             = "ScreenShareService"
        private const val LOVENSE_BUZZ_LEVEL = 10 // 0–20

        private val VIBRATE_VIEWER_JOIN  = longArrayOf(0, 80)
        private val VIBRATE_BUZZ_DEFAULT = longArrayOf(0, 80, 50, 80)
        private val VIBRATE_EMOJI        = longArrayOf(0, 30)
    }
}
